# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://benjiyamin.github.io
title: B. K. Miller
email: benjiyamin@gmail.com
author: Benjamin Miller
description: > # "Write an awesome description for your new site here. 
  Welcome to my online GitHub portfolio. You'll see some of the projects, skills, and ideas that I'd like to share
  with the world. Please feel free to contact me if you'd like to get in touch or collaborate. Cheers!
copyright: 'Copyright &copy; 2016 Ben Miller. All Rights Reserved.'
credits: >
  Credits: Landing Page is a free to use, open source Bootstrap theme created by
  <a href="http://startbootstrap.com/">Start Bootstrap</a>.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - features

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/benjiyamin
  - title: github
    url: https://github.com/benjiyamin
  - title: linkedin
    url: https://linkedin.com/in/benjaminkennethmiller
